apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  labels:
    app: portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: denisratenok/portal
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: portal
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal
  name: portal
spec:
  type: LoadBalancer
  selector:
    app: portal
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000

