apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-keycloak-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/poebos/keycloak-psql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-post-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-keycloak-secret
  labels:
    app: postgres-keycloak
data:
  POSTGRES_DB: keycloak
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-keycloak
  template:
    metadata:
      labels:
        app: postgres-keycloak
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: postgres-keycloak
          image: postgres:15.3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-keycloak-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-keycloak-data
      volumes:
        - name: postgres-keycloak-data
          persistentVolumeClaim:
            claimName: postgres-keycloak-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-keycloak
  name: postgres-keycloak
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres-keycloak
  type: LoadBalancer
